name: Pixel Pump Local

on:
  push:
    branches:
      - dev

jobs:
  local-dev-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: "pixel-pump-firmware"
    - uses: actions/checkout@v2
      with:
        repository: micropython/micropython
        ref: '294baf52b346e400e2255c6c1e82af5b978b18f7' # v1.20 tag
        path: "./micropython"
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install packages
      run: sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake git python3 -y
    - name: Apply HID fix
      run: |
        cd $GITHUB_WORKSPACE/micropython/
        git apply -v --ignore-space-change --ignore-whitespace $GITHUB_WORKSPACE/drivers/rp2_hid/0001-shared-tinyusb-Add-USB-HID-support.patch
    - name: Apply USB strings and enable HID fix
      run: |
        cd $GITHUB_WORKSPACE/micropython/
        git apply -v --ignore-space-change --ignore-whitespace $GITHUB_WORKSPACE/drivers/rp2_hid/0001-ports-rp2-boards-PICO-Use-Pixel-Pump-USB-strings-and.patch
    - name: Build blank MicroPython firmware (without Pixel Pump files)
      run: |
        cd $GITHUB_WORKSPACE/micropython/
        make -C mpy-cross
        git submodule update --init lib/pico-sdk lib/tinyusb
        make -C ports/rp2 BOARD=PICO
        mv $GITHUB_WORKSPACE/micropython/ports/rp2/build-PICO/firmware.uf2 $GITHUB_WORKSPACE/micropython/ports/rp2/build-PICO/firmware-blank.uf2
    - name: Generate Version File
      run: |
        python3 $GITHUB_WORKSPACE/tools/generateVersionFile.py --output $GITHUB_WORKSPACE/src/version.py --repo $GITHUB_WORKSPACE
    - name: Copy Pixel Pump firmware to MicroPython
      run: |
        cp -a $GITHUB_WORKSPACE/src/. $GITHUB_WORKSPACE/micropython/ports/rp2/modules/
    - name: Build Pixel Pump Firmware
      run: |
        cd $GITHUB_WORKSPACE/micropython/
        make -C ports/rp2 BOARD=PICO



